# Generated by Django 5.1.2 on 2024-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=40)),
                (
                    "product_image",
                    models.ImageField(null=True, upload_to="product_image/"),
                ),
                ("product_price", models.CharField(max_length=20)),
                ("product_discription", models.CharField(max_length=40)),
            ],
        ),
    ]
