# Generated by Django 5.1.2 on 2024-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0004_query"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=40)),
                ("message_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
