# Generated by Django 5.1.2 on 2024-10-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0005_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(max_length=20),
        ),
    ]
