# Generated by Django 5.1.2 on 2024-10-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0006_alter_product_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=40)),
                ("mobile_number", models.IntegerField()),
                ("expiry_date", models.DateField()),
                ("cvv", models.IntegerField()),
                ("account_holder_name", models.CharField(max_length=40)),
            ],
        ),
    ]
