# Generated by Django 5.1.2 on 2024-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0007_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_to_pay",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="product", name="product_price", field=models.IntegerField(),
        ),
    ]
